### ISSUE TITLE
merge-and-fork-detector failed to detect a merge

### ISSUE THREAD

**Issue by taras** [thefrontside/actions#9]
I merged a [Pull Request in Microstates](https://github.com/microstates/microstates.js/pull/369) repo but the publish failed because of the following error.

<img width="1301" alt="image" src="https://user-images.githubusercontent.com/74687/66236145-b1f0c880-e6bf-11e9-8bcc-04236f051f14.png">

The problem is that the merge did not include a PR in the title. The commit history looks like this,

<img width="822" alt="image" src="https://user-images.githubusercontent.com/74687/66236175-c7fe8900-e6bf-11e9-8d84-cf8b6cc7f172.png">

https://github.com/microstates/microstates.js/runs/248444449

**Comment by minkimcello** [comment]
@taras This was initially the intended behaviour as we assumed there shouldn't be any direct commits to master aside from merges. Without the merge number it wouldn't know which label to apply to the npm version. That's why we were hoping to have neutral exit codes so that it doesn't look like an error.

But right now I'm refactoring all of that so all commits to the specified branch is published. But the dev is expected to increment the package version manually.

**Comment by taras** [comment]
oh, interesting. ok

**Comment by minkimcello** [comment]
`merge-and-fork-detector` action deprecated in [PR#13](https://github.com/thefrontside/actions/pull/13).
